---
# @author Team 31, Melborune, 2022
#
# Bingzhe Jin (1080774), Hongwei Chen (891632), Tian Hui (1054513),
# Zhen Cai (1049487), Ziqi Zhang (1241157)

- name: Create volume snapshot(s)
  openstack.cloud.volume_snapshot:
    state: present
    volume: "{{ item.vol_name }}"
    display_name: "{{ item.vol_name }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: "{{ availability_zone }}"
  loop: "{{ volumes }}"
