---
# @author Team 31, Melborune, 2022
#
# Bingzhe Jin (1080774), Hongwei Chen (891632), Tian Hui (1054513),
# Zhen Cai (1049487), Ziqi Zhang (1241157)

- name: Create volumes
  openstack.cloud.volume:
    display_name: "{{ item.vol_name }}"
    size: "{{ item.vol_size }}"
    availability_zone: "{{ availability_zone }}"
    wait: yes
    timeout: 600
    state: present
  loop: "{{ volumes }}"
  register: os_vol

- debug:
    msg: "Volumes {{ os_vol.results | map(attribute='id') | list }} have been created."
