---
# @author Team 31, Melborune, 2022
#
# Bingzhe Jin (1080774), Hongwei Chen (891632), Tian Hui (1054513),
# Zhen Cai (1049487), Ziqi Zhang (1241157)

- name: Create security groups
  openstack.cloud.security_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
  loop: "{{ security_groups }}"

- debug:
    msg: "Security groups {{ security_groups | map(attribute='name') | list }} have been created."

- name: Create the first two security group rules
  openstack.cloud.security_group_rule:
    security_group: "{{ item.name }}"
    protocol: "{{ item.rules.protocol }}"
    port_range_min: "{{ item.rules.port_range_min }}"
    port_range_max: "{{ item.rules.port_range_max }}"
    remote_ip_prefix: "{{ item.rules.remote_ip_prefix }}"
    state: present
  loop: "{{ security_groups[:2] }}"

- name: Create the third (internal) security group rule
  openstack.cloud.security_group_rule:
    security_group: "{{ security_groups[2].name }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_group: "{{ item.remote_group }}"
    state: present
  loop: "{{ security_groups[2].rules }}"
