---
# @author Team 31, Melborune, 2022
#
# Bingzhe Jin (1080774), Hongwei Chen (891632), Tian Hui (1054513),
# Zhen Cai (1049487), Ziqi Zhang (1241157)

- name: Create OpenStack instances on MRC
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/openstack.yaml
  roles:
    - role: openstack/common
    - role: openstack/key
    - role: openstack/security-group
    - role: openstack/volume
    - role: openstack/instance

- hosts: mrc
  gather_facts: true
  roles:
    - role: setup/mount-volume
    - role: setup/docker
